# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2, verbose_name='country code')),
                ('region_code', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='region code')),
                ('data', jsonfield.fields.JSONField(verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='TaxCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', jsonfield.fields.JSONField(verbose_name='types')),
            ],
        ),
    ]
